### ISSUE TITLE
Issues using Equirectangular to Nadir/Zenith filter

### ISSUE THREAD

**Issue by Volkodlak** [dtschump/gmic#205]
Hi,
I'm using the Equirectangular to Nadir/Zenith filter to edit  panoramic photography in gimp ( windows 10).

But, since a moment, with latest updates of gmic, image is not processed correctly:
![Processed](https://user-images.githubusercontent.com/204653/78573535-bf2e7180-7820-11ea-9ab4-74b6a96b2bcf.jpg)

I've an old working version of Gmic (2.4.2_pre#181112), here:
https://drive.google.com/open?id=1K2JfLIKI6mYLl6YSbjcxyzHMGEvM0wiq

What do you think?

Have a nice day.

**Comment by dtschump** [comment]
Is it fixed with latest version?

**Comment by Volkodlak** [comment]
Hi, 
What do you meen by latest version, gimp, g'mic?
I've tried with both of them, updating filter list of g'mic.
I still have problem, but I can see a change in the version number of your filter.
![G'MIC-Qt for GIMP 2 10 - Windows 64 bits - 2 9 1 18_06_2020 12_53_44](https://user-images.githubusercontent.com/204653/85017219-09a66580-b163-11ea-899c-71d2998363ed.png)

Did i mess something?

**Comment by Volkodlak** [comment]
yeah! works great. Thanks for your work!
